# Schema for the configuration files of the Ximilar API module.
ximilar_api.settings:
  type: config_object
  label: 'Ximilar API settings'
  mapping:
    example:
      type: string
      label: 'Example'
